<?php

namespace CodersLabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupingRepository extends EntityRepository
{
}
